


CREATE TABLE IF NOT EXISTS levelRoleSet(
levelIdx INT,
role INT
);



CREATE TABLE IF NOT EXISTS member(
memberId BIGINT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
name VARCHAR(100) NOT NULL,
phoneNum VARCHAR(100) NOT NULL,
createAt DATETIME NOT NULL,
modifyAt DATETIME,
ip VARCHAR(255) NOT NULL,
levelIdx INT NOT NULL,
unique (email)
);

INSERT INTO member VALUES(1, 'user@naver.com', SHA2('111', 256), 'user1', '01012341234', NOW(), NULL, '192.168.0.1', 1)






CREATE TABLE IF NOT EXISTS category(
cateId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(100) NOT NULL,
isDrop CHAR(1) DEFAULT 0,
isShow CHAR(1) DEFAULT 1
);




CREATE TABLE IF NOT EXISTS board(
boardId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
isNotice CHAR(1) DEFAULT 0,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
contentHTML TEXT NOT NULL,
isSecret CHAR(1) DEFAULT 0,
writer VARCHAR(255) NOT NULL,
createAt DATETIME NOT NULL,
modifyer VARCHAR(255),
modifyAt DATETIME,
cateId BIGINT NOT NULL,
memberId BIGINT NOT NULL,

CONSTRAINT FK_category_board FOREIGN KEY (cateId) REFERENCES category(cateId),
CONSTRAINT FK_member_board FOREIGN KEY (memberId) REFERENCES member(memberId)
);



CREATE TABLE IF NOT EXISTS attachFile(
fileId BIGINT PRIMARY KEY AUTO_INCREMENT,
fileName VARCHAR(255) NOT NULL,
fileSize INT NOT NULL,
orgName VARCHAR(255) NOT NULL,
createAt DATETIME NOT NULL,
modifyAt DATETIME,
downCnt INT DEFAULT 0,
boardId BIGINT NOT NULL,
memberId BIGINT NOT NULL,
CONSTRAINT FK_board_attach FOREIGN KEY (boardId) REFERENCES board(boardId),
CONSTRAINT FK_member_attach FOREIGN KEY (memberId) REFERENCES member(memberId)
);


CREATE TABLE IF NOT EXISTS comment(
commentId BIGINT PRIMARY KEY AUTO_INCREMENT,
parentId INT default 0,
content VARCHAR(255) NOT NULL,
writer VARCHAR(255) NOT NULL,
modifyer VARCHAR(255),
createAt DATETIME NOT NULL,
modifyAt DATETIME,
boardId BIGINT,
memberId BIGINT,
CONSTRAINT FK_board_comment FOREIGN KEY (boardId) REFERENCES board(boardId),
CONSTRAINT FK_member_comment FOREIGN KEY (memberId) REFERENCES member(memberId)
);


CREATE TABLE IF NOT EXISTS log(
logId BIGINT PRIMARY KEY AUTO_INCREMENT,
content VARCHAR(255) NOT NULL,
ip VARCHAR(100) NOT NULL,
userEmail VARCHAR(255) NOT NULL,
createAt DATETIME NOT NULL,
modifyAt DATETIME
);




