# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
name: Gradle Package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
    - uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        gradle-version: 8.2.1
        build-root-directory : ./demo
        arguments: build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cicdsample
        path: ./demo/build/libs/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: cicdsample
      with:
        name: cicdsample
        path: ./demo/build/libs/*.jar
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: scp *.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/volume1/docker/
    
